name: web_app
description: An absolute bare-bones web app.
version: 1.0.0
resolution: workspace
publish_to: none

environment:
  sdk: ^3.8.0-133.0.dev

# Add regular dependencies here.
dependencies:
  web: ^0.5.1
  server:
    path: ../server
  wikipedia:
    path: ../wikipedia

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^5.0.0
